import { ClerkProvider } from '@clerk/nextjs'
import { currentUser } from '@clerk/nextjs'
import type { Metadata } from 'next'
import {
  Box,
  Grid,
  GridItem,
  UIProvider,
  colorModeManager,
  extendConfig,
  ThemeConfig,
} from '@yamada-ui/react'
import LeftSidebar from '@/components/shared/LeftSidebar'
import RightSidebar from '@/components/shared/RightSidebar'
import { ColorModeScript } from '@yamada-ui/core'
import Menubar from '@/components/shared/Menubar'
import Topbar from '@/components/shared/Topbar'

export const metadata: Metadata = {
  title: 'posotto',
  description: 'Generated by create next app',
}
export const fetchCache = 'default-no-store'

export const dynamic = 'force-dynamic'

// const customConfig = extendConfig({ breakpoint: 'up' })

const config: ThemeConfig = {
  initialColorMode: 'light',
  disableTransitionOnChange: false,
  var: { prefix: 'ui' },
  breakpoint: 'up',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = await currentUser()
  const userData = {
    id: user?.id || '',
    name: user?.firstName || '',
    imageUrl: user?.imageUrl || '',
  }
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <ColorModeScript type="cookie" nonce="testing" />
          <UIProvider
            colorModeManager={{ ...colorModeManager }.cookieStorage}
            config={config}
          >
            <Topbar />
            <Box w="full">
              <Grid
                templateColumns={{ base: '0fr auto 0fr', lg: '1fr auto 1fr' }}
              >
                <GridItem borderRight="1px solid" borderColor="gray.200">
                  <LeftSidebar />
                </GridItem>
                <GridItem w={{ base: 'full', lg: '61em' }} py="6em">
                  {children}
                </GridItem>
                <GridItem borderLeft="1px solid" borderColor="gray.200">
                  <RightSidebar />
                </GridItem>
              </Grid>
            </Box>
            <Menubar user={userData} />
          </UIProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
