import type { Metadata } from 'next'
import {
  Box,
  Grid,
  GridItem,
  UIProvider,
  colorModeManager,
} from '@yamada-ui/react'
import LeftSidebar from '@/components/LeftSidebar'
import RightSidebar from '@/components/RightSidebar'
import { ColorModeScript } from '@yamada-ui/core'
import Menubar from '@/components/Menubar'
import Topbar from '@/components/Topbar'

export const metadata: Metadata = {
  title: 'posotto',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ColorModeScript type="cookie" nonce="testing" />
        <UIProvider colorModeManager={{ ...colorModeManager }.cookieStorage}>
          <Topbar />
          <Box w="full">
            <Grid templateColumns="1fr auto 1fr">
              <GridItem borderRight="1px solid" borderColor="gray.200">
                <LeftSidebar />
              </GridItem>
              <GridItem minWidth="600px" py="6em">
                {children}
              </GridItem>
              <GridItem borderLeft="1px solid" borderColor="gray.200">
                <RightSidebar />
              </GridItem>
            </Grid>
          </Box>
          <Menubar />
        </UIProvider>
      </body>
    </html>
  )
}
